import numpy as np
import os
os.chdir('C:/Users/DELL/Desktop/Luis/Pset2')
import matplotlib.pyplot as plt
import K_S_Labor_Q3 as ks

ks1 = ks.K_S(N_k = 50)
V_Mat, gk_Mat, gn_Mat, pos_k_Mat, pos_n_Mat = ks1.Start_VFI()

f, (ax1, ax2) = plt.subplots(1,2)
f.set_figheight(5)
f.set_figwidth(10)
ax1.plot(ks1.grid_k, gn_Mat[0][:,1],'b', label = 'Employement, K=15')
ax1.plot(ks1.grid_k, gn_Mat[-1][:,1],'r', label = 'Employement, K=40')
ax1.legend(loc = 'upper right')
ax1.set_xlabel('Intensive Margin')
ax1.set_ylabel('Capital Today')
ax1.set_title('Policy Functions, Expansion')
ax2.plot(ks1.grid_k, gn_Mat[0][:,3],'b', label = 'Employement, K=15')
ax2.plot(ks1.grid_k, gn_Mat[-1][:,3],'r', label = 'Employement, K=40')
ax2.legend(loc = 'upper right')
ax2.set_xlabel('Intensive Margin')
ax2.set_ylabel('Capital Today')
ax2.set_title('Policy Functions, Recession')

f2, (gax1, gax2) = plt.subplots(1,2)
f2.set_figheight(5)
f2.set_figwidth(10)
gax1.plot(ks1.grid_k, gk_Mat[0][:,0],'b', label = 'Capital, e=0, K=15')
gax1.plot(ks1.grid_k, gk_Mat[0][:,1],'g', label = 'Capital, e=1, K=15')
gax1.plot(ks1.grid_k, gk_Mat[-1][:,0],'r', label = 'Capital, e=0, K=40')
gax1.plot(ks1.grid_k, gk_Mat[-1][:,1],'k', label = 'Capital, e=1, K=40')
gax1.legend(loc = 'upper right')
gax1.set_xlabel('Capital Tomorrow')
gax1.set_ylabel('Capital Today')
gax1.set_title('Policy Functions, Expansion')
gax2.plot(ks1.grid_k, gk_Mat[0][:,2],'b', label = 'Capital, e=0, K=15')
gax2.plot(ks1.grid_k, gk_Mat[0][:,3],'g', label = 'Capital, e=1, K=15')
gax2.plot(ks1.grid_k, gk_Mat[-1][:,2],'r', label = 'Capital, e=0, K=40')
gax2.plot(ks1.grid_k, gk_Mat[-1][:,3],'k', label = 'Capital, e=1, K=40')
gax2.legend(loc = 'upper right')
gax2.set_xlabel('Capital Tomorrow')
gax2.set_ylabel('Capital Today')
gax2.set_title('Policy Functions, Recession')


f3, (hax1, hax2) = plt.subplots(1,2)
f3.set_figheight(5)
f3.set_figwidth(10)
hax1.plot(ks1.grid_k, V_Mat[0][:,0],'b', label = 'Value, e=0, K=15')
hax1.plot(ks1.grid_k, V_Mat[0][:,1],'g', label = 'Value, e=1, K=15')
hax1.plot(ks1.grid_k, V_Mat[-1][:,0],'r', label = 'Value, e=0, K=40')
hax1.plot(ks1.grid_k, V_Mat[-1][:,1],'k', label = 'Value, e=1, K=40')
hax1.legend(loc = 'upper right')
hax1.set_xlabel('Capital Tomorrow')
hax1.set_ylabel('Capital Today')
hax1.set_title('Value Function, Expansion')
hax2.plot(ks1.grid_k, V_Mat[0][:,2],'b', label = 'Value, e=0, K=15')
hax2.plot(ks1.grid_k, V_Mat[0][:,3],'g', label = 'Value, e=1, K=15')
hax2.plot(ks1.grid_k, V_Mat[-1][:,2],'r', label = 'Value, e=0, K=40')
hax2.plot(ks1.grid_k, V_Mat[-1][:,3],'k', label = 'Value, e=1, K=40')
hax2.legend(loc = 'upper right')
hax2.set_xlabel('Capital Tomorrow')
hax2.set_ylabel('Capital Today')
hax2.set_title('Value Functions, Recession')